;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Damage.Type.Senergy",DevComment="")
+GameplayTagList=(Tag="Damage.Type.Synergy",DevComment="")
+GameplayTagList=(Tag="Data.Damage.Duration",DevComment="")
+GameplayTagList=(Tag="Event.BlackHole",DevComment="")
+GameplayTagList=(Tag="Event.Damage",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Attack",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Attack.Fist.Left",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Attack.Melee",DevComment="")
+GameplayTagList=(Tag="Event.Projectile",DevComment="")
+GameplayTagList=(Tag="Event.Teleport",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Ability.Skill.Beam",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Ability.Skill.Teleport",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Mark.Mage",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Mark.Warrior",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Projectile.Warrior",DevComment="")
+GameplayTagList=(Tag="GameplayCue.RangedImpact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Skill.FrostAttack",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Synergy.Explosion",DevComment="")
+GameplayTagList=(Tag="GameplayCue/Mark.Warrior",DevComment="")

